[project]
name = "customs-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yuthana", email = "chayutha2014@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "lxml>=6.1.3",
    "opencv-python-headless>=5.0.0.93",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "pdfplumber>=0.11.10",
    "pillow>=12.3.0",
    "pymupdf>=1.28.2",
    "pytesseract>=0.3.13",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "rapidocr-onnxruntime>=1.4.4",
    "xlrd>=2.0.2",
]

[project.scripts]
customs-checker = "customs_checker:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
